server:
  port: 11115
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:11140/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
spring:
  application:
    name: inventory-service
  data:
    mongodb:
      host: 192.168.99.100

csv.config.path: /config.properties